; PhonePlus (iPod) Konfiguration
; Tasten = Windows-Keys-Namen (F4, B, V, NumPad5, ...)
[Settings]
MenuKey=F4
EatKey=B
VestKey=V
AutoVest=True
AutoVestBelow=20

[Prices]
Snack=5
Meal=15
Vest=500

[Models]










1=815.0,295.0,5.8,Westen-Shop #1 (Händlerplatz Broker)
2=716.0,1510.0,14.6,Westen-Shop #2 (Händlerplatz Bohan)
3=61.0,815.0,14.4,Westen-Shop #3 (Händlerplatz Algonquin)
4=-1465.0,1152.0,22.9,Westen-Shop #4 (Händlerplatz Alderney)
5=-140.0,-818.0,4.8,Westen-Shop #5 (Händlerplatz Broker-Süd)
6=-1194.0,-180.0,4.0,Westen-Shop #6 (Händlerplatz Alderney-West)

[SnackVendors]
1=444.14,1519.24,16.3,Snack-Shop: Fortside Burger
2=1651.9,226.0,25.0,Snack-Shop: Bc Burger
3=-441.06,1191.76,12.9,Snack-Shop: Nh Burger
4=-174.5,275.1,14.8,Snack-Shop: Sj Burger
5=-135.9,72.6,14.8,Snack-Shop: Triangle Cluck
6=882.46,-478.36,15.9,Snack-Shop: Diner 69
7=1134.4,331.2,29.8,Snack-Shop: Ch Ron Gas
8=1783.56,830.86,16.6,Snack-Shop: Mp Ron
9=-1312.26,1746.14,27.9,Snack-Shop: Westdyke Ron

[VestVendors]
1=815.0,295.0,5.8,Westen-Shop #1 (Händlerplatz Broker)
2=716.0,1510.0,14.6,Westen-Shop #2 (Händlerplatz Bohan)
3=61.0,815.0,14.4,Westen-Shop #3 (Händlerplatz Algonquin)
4=-1465.0,1152.0,22.9,Westen-Shop #4 (Händlerplatz Alderney)
5=-140.0,-818.0,4.8,Westen-Shop #5 (Händlerplatz Broker-Süd)
6=-1194.0,-180.0,4.0,Westen-Shop #6 (Händlerplatz Alderney-West)
